/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WasserRouteImport } from './routes/wasser'
import { Route as StadtRouteImport } from './routes/stadt'
import { Route as IndexRouteImport } from './routes/index'

const WasserRoute = WasserRouteImport.update({
  id: '/wasser',
  path: '/wasser',
  getParentRoute: () => rootRouteImport,
} as any)
const StadtRoute = StadtRouteImport.update({
  id: '/stadt',
  path: '/stadt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stadt': typeof StadtRoute
  '/wasser': typeof WasserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stadt': typeof StadtRoute
  '/wasser': typeof WasserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stadt': typeof StadtRoute
  '/wasser': typeof WasserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stadt' | '/wasser'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stadt' | '/wasser'
  id: '__root__' | '/' | '/stadt' | '/wasser'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StadtRoute: typeof StadtRoute
  WasserRoute: typeof WasserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wasser': {
      id: '/wasser'
      path: '/wasser'
      fullPath: '/wasser'
      preLoaderRoute: typeof WasserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadt': {
      id: '/stadt'
      path: '/stadt'
      fullPath: '/stadt'
      preLoaderRoute: typeof StadtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StadtRoute: StadtRoute,
  WasserRoute: WasserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
